<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \TwoFactorAuth\Form\TokenForm $formToken
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$pageTitle = $plugins->get('pageTitle');

$this->htmlElement('body')->appendAttribute('class', 'login login-token');
?>

<?= $pageTitle($translate('Log in (2FA)')) ?>

<div class="two-factor-auth-login">

    <?= $this->messages() ?>

    <?= $this->form($formToken) ?>

</div>
