<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \TwoFactorAuth\Form\TokenForm $formToken
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
?>

<dialog id="login-token" class="popup popup-dialog dialog-login-token">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button" title="<?= $translate('Close') ?>" autofocus="autofocus">
                    <span class="dialog-close">🗙</span>
                </button>
            </div>
            <div class="dialog-contents">
                <?= $this->form($formToken) ?>
            </div>
            <div class="dialog-footer">
                <button class="resend-code" type="button" data-url-resend-code="<?= $url('login') ?>">
                    <?= $translate('Resend a code') ?>
                </button>
            </div>
        </div>
    </div>
</dialog>
