<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \TwoFactorAuth\Form\TokenForm $form
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
?>

<dialog id="2fa-token" class="popup popup-dialog dialog-2fa-token" aria-label="<?= $this->escapeHtmlAttr($translate('Two-factor authentication')) ?>">
    <div class="dialog-background">
        <div class="dialog-panel">
            <div class="dialog-header">
                <button type="button" class="dialog-header-close-button">
                    <span class="dialog-close" aria-hidden="true">🗙</span>
                    <span class="dialog-close-label"><?= $this->translate('Close') ?></span>
                </button>
                <div class="dialog-messages" role="status" aria-live="polite">
                </div>
            </div>
            <div class="dialog-contents">
                <?= $this->form($form) ?>
            </div>
            <div class="dialog-footer">
                <button class="resend-code" type="button" data-url="<?= $url('login') ?>">
                    <?= $translate('Resend a code') ?>
                </button>
            </div>
        </div>
    </div>
</dialog>
